version: '3.6'

volumes:
  zookeeper-data:
    driver: local
  zookeeper-log:
    driver: local
  kafka-data:
    driver: local

services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-log:/var/lib/zookeeper/log
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka
    volumes:
      # - kafka-data:/var/lib/kafka
      - type: tmpfs
        target: /var/lib/kafka
        tmpfs:
          size: 1000
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_NUM_PARTITIONS: 12
      KAFKA_COMPRESSION_TYPE: gzip
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: 'false'
      KAFKA_JMX_PORT: 9091
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    links:
      - zookeeper

  producer:
    image: confluentinc/cp-kafkacat
    working_dir: /app
    volumes:
      - ./:/app
      - type: tmpfs
        target: /tmpfs
        tmpfs:
          size: 1000
    command: 
      - bash 
      - -c 
      - |
        cp /app/KDDTe5Classes_cassales.csv /tmpfs ;
        kafkacat -P -b kafka:9092 -t minas-control -c 1 ;
        echo "producing_load\n" ;
        echo "producing_load\n" | kafkacat -P -b kafka:9092 -t minas-control -c 1;
        kafkacat -P -b kafka:9092 -t minas-source -l /tmpfs/KDDTe5Classes_cassales.csv
    links:
      - kafka
